// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `api`, `build_snapshot`, `build_status_string`, `file_infos`, `is_paused`, `looks_like_url`, `snapshot_for`

/// Starts the librqbit session. [download_dir] is the default output folder.
Future<void> torrentInit({required String downloadDir}) =>
    RustLib.instance.api.crateApiTorrentTorrentInit(downloadDir: downloadDir);

/// Adds a torrent from a magnet/URL or a local `.torrent` file path, saving
/// into [save_path]. Returns the new torrent id.
Future<int> torrentAdd({required String source, required String savePath}) =>
    RustLib.instance.api.crateApiTorrentTorrentAdd(
      source: source,
      savePath: savePath,
    );

/// Lists all torrents with their current stats.
Future<List<TorrentSnapshot>> torrentList() =>
    RustLib.instance.api.crateApiTorrentTorrentList();

/// Returns the current stats for a single torrent id.
Future<TorrentSnapshot> torrentStats({required int id}) =>
    RustLib.instance.api.crateApiTorrentTorrentStats(id: id);

/// Lists the files contained in a torrent (empty until metadata arrives).
/// Synchronous because it only reads in-memory metadata.
List<TorrentFileInfo> torrentFiles({required int id}) =>
    RustLib.instance.api.crateApiTorrentTorrentFiles(id: id);

Future<void> torrentPause({required int id}) =>
    RustLib.instance.api.crateApiTorrentTorrentPause(id: id);

Future<void> torrentResume({required int id}) =>
    RustLib.instance.api.crateApiTorrentTorrentResume(id: id);

/// Removes a torrent. When [delete_files] is true the downloaded data is also
/// deleted from disk; otherwise the torrent is just forgotten from the session.
Future<void> torrentDelete({required int id, required bool deleteFiles}) =>
    RustLib.instance.api.crateApiTorrentTorrentDelete(
      id: id,
      deleteFiles: deleteFiles,
    );

/// A single file inside a torrent.
class TorrentFileInfo {
  final int index;
  final String name;
  final String path;
  final PlatformInt64 size;

  const TorrentFileInfo({
    required this.index,
    required this.name,
    required this.path,
    required this.size,
  });

  @override
  int get hashCode =>
      index.hashCode ^ name.hashCode ^ path.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TorrentFileInfo &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          name == other.name &&
          path == other.path &&
          size == other.size;
}

/// A single torrent's state, mirroring what the old UI consumed.
class TorrentSnapshot {
  final int id;
  final String name;
  final String savePath;
  final String errorMsg;
  final String status;
  final double progress;
  final PlatformInt64 downloadRate;
  final PlatformInt64 uploadRate;
  final PlatformInt64 totalDone;
  final PlatformInt64 totalWanted;
  final PlatformInt64 totalUploaded;
  final int numPeers;
  final int numSeeds;
  final bool isPaused;
  final bool isFinished;
  final bool hasMetadata;

  const TorrentSnapshot({
    required this.id,
    required this.name,
    required this.savePath,
    required this.errorMsg,
    required this.status,
    required this.progress,
    required this.downloadRate,
    required this.uploadRate,
    required this.totalDone,
    required this.totalWanted,
    required this.totalUploaded,
    required this.numPeers,
    required this.numSeeds,
    required this.isPaused,
    required this.isFinished,
    required this.hasMetadata,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      savePath.hashCode ^
      errorMsg.hashCode ^
      status.hashCode ^
      progress.hashCode ^
      downloadRate.hashCode ^
      uploadRate.hashCode ^
      totalDone.hashCode ^
      totalWanted.hashCode ^
      totalUploaded.hashCode ^
      numPeers.hashCode ^
      numSeeds.hashCode ^
      isPaused.hashCode ^
      isFinished.hashCode ^
      hasMetadata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TorrentSnapshot &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          savePath == other.savePath &&
          errorMsg == other.errorMsg &&
          status == other.status &&
          progress == other.progress &&
          downloadRate == other.downloadRate &&
          uploadRate == other.uploadRate &&
          totalDone == other.totalDone &&
          totalWanted == other.totalWanted &&
          totalUploaded == other.totalUploaded &&
          numPeers == other.numPeers &&
          numSeeds == other.numSeeds &&
          isPaused == other.isPaused &&
          isFinished == other.isFinished &&
          hasMetadata == other.hasMetadata;
}
